# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='pokes',
        ),
        migrations.AddField(
            model_name='poke',
            name='users',
            field=models.ManyToManyField(to='poke_app.User'),
        ),
    ]
