# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0002_auto_20180130_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='users',
            field=models.ManyToManyField(related_name='pokers', to='poke_app.User'),
        ),
    ]
