# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0005_auto_20180130_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='pokers',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='pokes',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='users',
        ),
        migrations.AddField(
            model_name='poke',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='poke',
            name='poke_reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pokes_received', to='poke_app.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poke',
            name='poke_sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pokes_sent', to='poke_app.User'),
            preserve_default=False,
        ),
    ]
